{
	"version": 1486142549,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/spandaime-sheet0.png",
		"images/spandaime-sheet1.png",
		"images/tbguia.png",
		"images/sptamboresq-sheet0.png",
		"images/sptamboresq-sheet1.png",
		"images/spjogador-sheet0.png",
		"images/spjogador-sheet1.png",
		"images/sptambordir-sheet0.png",
		"images/spobjetocodigo-sheet0.png",
		"images/spfogo-sheet0.png",
		"images/spfogo-sheet1.png",
		"images/spbordainferior-sheet0.png",
		"images/spbordainferior-sheet1.png",
		"images/splimiteinferior-sheet0.png",
		"images/spchao-sheet0.png",
		"images/splimiteinferiormax-sheet0.png",
		"images/btvoltar-sheet0.png",
		"images/spderrota-sheet0.png",
		"images/sppiramide-sheet0.png",
		"images/spfundo1-sheet0.png",
		"images/spvitoria-sheet0.png",
		"images/spsuba-sheet0.png",
		"images/spfundo2-sheet0.png",
		"images/spnuvens-sheet0.png",
		"images/spplataforma-sheet0.png",
		"images/tiledbackground.png",
		"media/carrapicho-tic_tic_tac-x3yjfj.ogg",
		"media/jogo - kevin macleod - allada.ogg",
		"media/menu - kevin macleod - zanzibar.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}